# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7a5f995524441f78613ef96ffc31244554beab55b91a7b25d1cb5672e3840f33bbc3970702e0e218fe4be03348ca38f448328a7d0a6c4c5f4bca16e14bb9e5

test:
  secret_key_base: 4b391551f25e06abcb1db7a4694fa3aaeb1e501b7f36e6091a2ff673f5db34b27edf84aff51f72f853474290425c385732625c2be3507c2e8b8a57784da75dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
